name: Calendar Spider

on:
  workflow_dispatch:
    inputs:
      year:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: 'cd script'
      run: cd script

    - name: 'Gen New Year Calendar'
      run: go run main.go -year ${{ github.event.inputs.year }}

    - name: 'cd ..'
      run: cd ..
      
    - name: 'Show Diff'
      run: git add .
    
    - name: 'Push Calendar'
      uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
      with:
        commit-message: "new calendar"
        remote: origin